import XCTest
import AppKit
@testable import ClipboardManager

/// Covers the nspasteboard.org markers that keep password-manager secrets and other
/// transient items out of clipboard history.
final class ConcealedClipTests: XCTestCase {
    private var pasteboard: NSPasteboard!

    override func setUp() {
        super.setUp()
        pasteboard = NSPasteboard(name: NSPasteboard.Name("ConcealedClipTests-\(UUID().uuidString)"))
    }

    override func tearDown() {
        pasteboard.releaseGlobally()
        pasteboard = nil
        super.tearDown()
    }

    private func write(_ text: String, markers: [String]) {
        let markerTypes = markers.map { NSPasteboard.PasteboardType($0) }
        pasteboard.clearContents()
        pasteboard.declareTypes([.string] + markerTypes, owner: nil)
        pasteboard.setString(text, forType: .string)
        for type in markerTypes {
            pasteboard.setData(Data(), forType: type)
        }
    }

    func testShouldIgnore_ConcealedType_ReturnsTrue() {
        write("hunter2", markers: ["org.nspasteboard.ConcealedType"])
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: pasteboard.types))
    }

    func testShouldIgnore_TransientType_ReturnsTrue() {
        write("one-time code", markers: ["org.nspasteboard.TransientType"])
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: pasteboard.types))
    }

    func testShouldIgnore_AutoGeneratedType_ReturnsTrue() {
        write("generated", markers: ["org.nspasteboard.AutoGeneratedType"])
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: pasteboard.types))
    }

    func testShouldIgnore_LegacyVendorMarkers_ReturnTrue() {
        for marker in ["com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType"] {
            write("secret", markers: [marker])
            XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: pasteboard.types), marker)
        }
    }

    func testShouldIgnore_PlainText_ReturnsFalse() {
        write("ordinary text", markers: [])
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: pasteboard.types))
    }

    func testShouldIgnore_NilTypes_ReturnsFalse() {
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: nil))
    }
}
