import Cocoa

/// What the monitor should record for the current pasteboard contents.
enum CaptureDecision: Equatable {
    case ignore
    case tooLarge(kind: String, size: Int, limit: Int)
    case text(String)
    case richText(plainText: String, rtf: Data)
    case image(description: String, png: Data)
}

struct CaptureLimits {
    let maxTextBytes: Int
    let maxImageBytes: Int

    static var current: CaptureLimits {
        CaptureLimits(maxTextBytes: Preferences.maxClipSizeBytes, maxImageBytes: Preferences.maxImageSizeBytes)
    }
}

/// Decides how a pasteboard's contents should be captured. Kept free of monitor state so the
/// priority rules can be tested against a private pasteboard.
enum ClipboardCapture {
    /// Markers (see nspasteboard.org) that password managers and similar apps put on content
    /// that must never be written to clipboard history.
    static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    /// Representations are checked in order: files, rich text, images, then plain text.
    ///
    /// Files come first because Finder also puts the file's icon on the pasteboard as TIFF, and
    /// rich text beats images because Office and other apps attach a picture of copied text.
    static func decide(for pasteboard: NSPasteboard, limits: CaptureLimits) -> CaptureDecision {
        let types = pasteboard.types ?? []
        guard !types.contains(where: privateTypes.contains) else { return .ignore }

        let plainString = pasteboard.string(forType: .string)

        let fileURLs = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL] ?? []
        if !fileURLs.isEmpty {
            return textDecision(fileURLs.map(\.path).joined(separator: "\n"), limits: limits)
        }

        if let rtfData = pasteboard.data(forType: .rtf),
           let attributed = NSAttributedString(rtf: rtfData, documentAttributes: nil) {
            let plainText = plainString.flatMap { $0.isEmpty ? nil : $0 } ?? attributed.string
            if !plainText.isEmpty {
                return richTextDecision(plainText, rtf: rtfData, attributed: attributed, limits: limits)
            }
        }

        if let pngData = imagePNGData(from: pasteboard) {
            guard pngData.count <= limits.maxImageBytes else {
                return .tooLarge(kind: "Image", size: pngData.count, limit: limits.maxImageBytes)
            }
            let size = NSImage(data: pngData)?.size ?? .zero
            return .image(description: "[Image: \(Int(size.width))x\(Int(size.height))]", png: pngData)
        }

        return textDecision(plainString ?? "", limits: limits)
    }

    private static func textDecision(_ text: String, limits: CaptureLimits) -> CaptureDecision {
        guard !text.isEmpty else { return .ignore }
        let size = text.utf8.count
        guard size <= limits.maxTextBytes else {
            return .tooLarge(kind: "Text", size: size, limit: limits.maxTextBytes)
        }
        return .text(text)
    }

    private static func richTextDecision(
        _ plainText: String,
        rtf: Data,
        attributed: NSAttributedString,
        limits: CaptureLimits
    ) -> CaptureDecision {
        let textSize = plainText.utf8.count
        guard textSize <= limits.maxTextBytes else {
            return .tooLarge(kind: "Rich text", size: textSize, limit: limits.maxTextBytes)
        }
        // RTF from web pages and Mail can carry a formatting payload far larger than the text
        // itself. Keep the text rather than dropping the whole clip.
        guard rtf.count <= limits.maxTextBytes, !attributed.containsAttachments else {
            return .text(plainText)
        }
        return .richText(plainText: plainText, rtf: rtf)
    }

    /// PNG bytes for an image on the pasteboard, whether it was offered as PNG or TIFF.
    private static func imagePNGData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png), NSImage(data: png) != nil {
            return png
        }
        guard let tiff = pasteboard.data(forType: .tiff),
              let bitmap = NSBitmapImageRep(data: tiff) else {
            return nil
        }
        return bitmap.representation(using: .png, properties: [:])
    }
}
